{
 "title": "Quality check",
 "time": { "from": "2023-03-20T17:35:51.333Z", "to": "2023-05-19T03:33:24.458Z" },
 "templating": {
  "list": [
   { "name": "network", "label": "Choisir le réseau", "query": "${VAR_NETWORK}" },
   {
    "name": "station",
    "label": "Select station",
    "query": "select s.fullname\nfrom station s\ninner join station_network sn on s.id = sn.station_id\ninner join network n on n.id = sn.network_id\nwhere n.name = '$network';"
   },
   {
    "name": "constellation",
    "label": "Select constellation(s)",
    "query": "select fullname\nfrom constellation\norder by fullname;"
   },
   {
    "name": "observation_type",
    "label": "Select observable type(s)",
    "query": "select type\nfrom observation_type\norder by type;"
   }
  ]
 },
 "panels": [
  { "title": "Signal quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mean CNR - $station",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB-Hz" } },
   "targets": [
    {
     "rawSql": "select\r\n  $__time(\"date\"),\r\n  value as \" \",\r\n  c.shortname || 'S' || ot.type as \"band\"\r\nfrom\r\n  sig2noise\r\n  inner join station s on sig2noise.station_id = s.id\r\n  inner join constellation c on c.id = sig2noise.constellation_id\r\n  inner join observation_type ot on sig2noise.observation_type_id = ot.id\r\n  inner join station_network sn on sig2noise.station_id = sn.station_id\r\n  inner join network n on sn.network_id = n.id\r\nwhere\r\n  $__timeFilter(\"date\")\r\n  and s.fullname = '$station'\r\n  and c.fullname in (${constellation:sqlstring})\r\n  and ot.type in (${observation_type:sqlstring})\r\n  and n.name = '$network'\r\norder by\r\n  band desc;"
    }
   ]
  },
  {
   "title": "Mean code multipath - $station",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "rawSql": "select\r\n  $__time(\"date\"),\r\n  value as \" \",\r\n  c.shortname || 'M' || ot.type as \"band\"\r\nfrom\r\n  multipath mp\r\n  inner join station s on mp.station_id = s.id\r\n  inner join constellation c on c.id = mp.constellation_id\r\n  inner join observation_type ot on mp.observation_type_id = ot.id\r\n  inner join station_network sn on mp.station_id = sn.station_id\r\n  inner join network n on sn.network_id = n.id\r\nwhere\r\n  $__timeFilter(\"date\")\r\n  and s.fullname = '$station'\r\n  and c.fullname in (${constellation:sqlstring})\r\n  and ot.type in (${observation_type:sqlstring})\r\n  and n.name = '$network'\r\norder by\r\n  band desc;"
    }
   ]
  },
  { "title": "Cycle slip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Observation cycle slips - $station",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\r\n  $__time(\"date\"),\r\n  value as \" \",\r\n  c.fullname\r\nfrom\r\n  observation_cs\r\n  inner join station s on observation_cs.station_id = s.id\r\n  inner join constellation c on c.id = observation_cs.constellation_id\r\n  inner join station_network sn on observation_cs.station_id = sn.station_id\r\n  inner join network n on sn.network_id = n.id\r\nwhere\r\n  $__timeFilter(\"date\")\r\n  and s.fullname = '$station'\r\n  and c.fullname in (${constellation:sqlstring})\r\n  and n.name = '$network'\r\norder by\r\n  value desc;"
    }
   ]
  },
  {
   "title": "Satellite cycle slips - $station",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\r\n  $__time(\"date\"),\r\n  value as \" \",\r\n  c.fullname\r\nfrom\r\n  satellite_cs\r\n  inner join station s on satellite_cs.station_id = s.id\r\n  inner join constellation c on c.id = satellite_cs.constellation_id\r\n  inner join station_network sn on satellite_cs.station_id = sn.station_id\r\n  inner join network n on sn.network_id = n.id\r\nwhere\r\n  $__timeFilter(\"date\")\r\n  and s.fullname = '$station'\r\n  and c.fullname in (${constellation:sqlstring})\r\n  and n.name = '$network'\r\norder by\r\n  value desc;"
    }
   ]
  },
  { "title": "Sources et explications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Graph sources",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": {
    "content": "# Graph sources\n\n- Graphs are generated from the data quality metrics xtr files available at: [https://renag.resif.fr/pub/quality-check/full/](https://renag.resif.fr/pub/quality-check/full/)\n- The data quality metrics have been computed at the [RESIF-RENAG data center](https://doi.org/10.17616/R31NJN5L) using the [G-Nut/Anubis](https://gnutsoftware.com/software/anubis/) software\n- Input files and the daily RINEX 3 observation files available from: [https://renag.resif.fr/pub/rinex3/](https://renag.resif.fr/pub/rinex3/)"
   }
  },
  {
   "title": "Explanations",
   "type": "text",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "options": {
    "content": "# Explanations\n\n## Carrier-phase signal-to-noise ratio (dB-Hz)\n\nSignal strength of the modulated signal.\n\n## Pseudo-range multipath (cm)\n\nElongation of the signal arriving indirectly at the GNSS antenna.\n\n## Observation cycle slips (%)\n\nObservation tracking interruption rate.\n\n## Satellite cycle slips (%)\n\nSatellite tracking interruption rate.\n"
   }
  },
  {
   "title": "GNSS Stations",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "select\r\n  shortname as name,\r\n  -- n.name as network,\r\n  lat,\r\n  case\r\n    when long > 180 then long - 360\r\n    else long\r\n  end as long,\r\n  case\r\n    when shortname != '$station' then 0\r\n    when shortname = '$station' then 80\r\n  end as color\r\nfrom\r\n  station\r\n  inner join station_network sn on station.id = sn.station_id\r\n  inner join network n on n.id = sn.network_id\r\nwhere n.name = '$network'; "
    }
   ]
  }
 ]
}