{
 "title": "Skyplots",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "query": "${VAR_NETWORK}" },
   {
    "name": "station",
    "label": "Select station",
    "query": "select s.fullname\nfrom station s\ninner join station_network sn on s.id = sn.station_id\ninner join network n on n.id = sn.network_id\nwhere n.name = '$network';"
   },
   {
    "name": "constellation",
    "label": "Select constellation(s)",
    "query": "select fullname\nfrom constellation\n\norder by fullname;"
   },
   {
    "name": "day",
    "label": "Select day",
    "query": "select date::text\nfrom skyplot_date\nwhere $__timeFilter(\"date\")\norder by date;"
   }
  ]
 },
 "panels": [
  { "title": "Signal to noise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SNR1 (dB-Hz)",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select\r\n    90 - elevation as \"r\",\r\n    azimut as \"theta\",\r\n    sig2noise1 as \"value\",\r\n    'G' || to_char(satellite, 'fm00') as \"satellite\",\r\n    '$constellation' as \"constellation\"\r\nfrom\r\n    skyplot\r\n    inner join station s on s.id = skyplot.station_id\r\n    inner join constellation c on c.id = skyplot.constellation_id\r\n    inner join station_network sn on skyplot.station_id = sn.station_id\r\n    inner join network n on sn.network_id = n.id\r\n    inner join skyplot_date sd on date_id = sd.id\r\nwhere\r\n    s.fullname = '$station' and\r\n    c.fullname = '$constellation' and\r\n    sig2noise1 is not null and\r\n    n.name = '$network' and\r\n    sd.date = '$day';"
    }
   ]
  },
  {
   "title": "SNR2 (dB-Hz)",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "select\r\n  90 - elevation as \"r\",\r\n  azimut as \"theta\",\r\n  sig2noise2 as \"value\",\r\n  'G' || to_char(satellite, 'fm00') as \"satellite\",\r\n  '$constellation' as \"constellation\"\r\nfrom\r\n  skyplot\r\n  inner join station s on s.id = skyplot.station_id\r\n  inner join constellation c on c.id = skyplot.constellation_id\r\n  inner join station_network sn on skyplot.station_id = sn.station_id\r\n  inner join network n on sn.network_id = n.id\r\n  inner join skyplot_date sd on date_id = sd.id\r\nwhere\r\n  s.fullname = '$station'\r\n  and c.fullname = '$constellation'\r\n  and sig2noise2 is not null\r\n  and n.name = '$network'\r\n  and sd.date = '$day';"
    }
   ]
  },
  {
   "title": "SNR5 (dB-Hz)",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "select\r\n    90 - elevation as \"r\",\r\n    azimut as \"theta\",\r\n    sig2noise5 as \"value\",\r\n    'G' || to_char(satellite, 'fm00') as \"satellite\",\r\n    '$constellation' as \"constellation\"\r\nfrom\r\n    skyplot\r\n    inner join station s on s.id = skyplot.station_id\r\n    inner join constellation c on c.id = skyplot.constellation_id\r\n    inner join station_network sn on skyplot.station_id = sn.station_id\r\n    inner join network n on sn.network_id = n.id\r\n    inner join skyplot_date sd on date_id = sd.id\r\nwhere\r\n    s.fullname = '$station' and\r\n    c.fullname = '$constellation' and\r\n    sig2noise5 is not null and\r\n    n.name = '$network' and\r\n    sd.date = '$day';"
    }
   ]
  },
  { "title": "Multipath", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "MP1 (cm)",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select\r\n    90 - elevation as \"r\",\r\n    azimut as \"theta\",\r\n    mp1 as \"value\",\r\n    'G' || to_char(satellite, 'fm00') as \"satellite\",\r\n    '$constellation' as \"constellation\"\r\nfrom\r\n    skyplot\r\n    inner join station s on s.id = skyplot.station_id\r\n    inner join constellation c on c.id = skyplot.constellation_id\r\n    inner join station_network sn on skyplot.station_id = sn.station_id\r\n    inner join network n on sn.network_id = n.id\r\n    inner join skyplot_date sd on date_id = sd.id\r\nwhere\r\n    s.fullname = '$station' and\r\n    c.fullname = '$constellation' and\r\n    mp1 is not null and\r\n    n.name = '$network' and\r\n    sd.date = '$day';"
    }
   ]
  },
  {
   "title": "MP2 (cm)",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "rawSql": "select\r\n    90 - elevation as \"r\",\r\n    azimut as \"theta\",\r\n    mp2 as \"value\",\r\n    'G' || to_char(satellite, 'fm00') as \"satellite\",\r\n    '$constellation' as \"constellation\"\r\nfrom\r\n    skyplot\r\n    inner join station s on s.id = skyplot.station_id\r\n    inner join constellation c on c.id = skyplot.constellation_id\r\n    inner join station_network sn on skyplot.station_id = sn.station_id\r\n    inner join network n on sn.network_id = n.id\r\n    inner join skyplot_date sd on date_id = sd.id\r\nwhere\r\n    s.fullname = '$station' and\r\n    c.fullname = '$constellation' and\r\n    mp2 is not null and\r\n    n.name = '$network' and\r\n    sd.date = '$day';"
    }
   ]
  },
  {
   "title": "MP5 (cm)",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "rawSql": "select\r\n    90 - elevation as \"r\",\r\n    azimut as \"theta\",\r\n    mp5 as \"value\",\r\n    'G' || to_char(satellite, 'fm00') as \"satellite\",\r\n    '$constellation' as \"constellation\"\r\nfrom\r\n    skyplot\r\n    inner join station s on s.id = skyplot.station_id\r\n    inner join constellation c on c.id = skyplot.constellation_id\r\n    inner join station_network sn on skyplot.station_id = sn.station_id\r\n    inner join network n on sn.network_id = n.id\r\n    inner join skyplot_date sd on date_id = sd.id\r\nwhere\r\n    s.fullname = '$station' and\r\n    c.fullname = '$constellation' and\r\n    mp5 is not null and\r\n    n.name = '$network' and\r\n    sd.date = '$day';"
    }
   ]
  },
  { "title": "Cycle slip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CS1",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select\r\n    90 - elevation as \"r\",\r\n    azimut as \"theta\",\r\n    'G' || to_char(satellite, 'fm00') as \"satellite\",\r\n    '$constellation' as \"constellation\"\r\nfrom\r\n    skyplot\r\n    inner join station s on s.id = skyplot.station_id\r\n    inner join constellation c on c.id = skyplot.constellation_id\r\n    inner join station_network sn on skyplot.station_id = sn.station_id\r\n    inner join network n on sn.network_id = n.id\r\n    inner join skyplot_date sd on date_id = sd.id\r\nwhere\r\n    cs1 and\r\n    s.fullname = '$station' and\r\n    c.fullname = '$constellation' and\r\n    n.name = '$network' and\r\n    sd.date = '$day';"
    }
   ]
  },
  {
   "title": "CS2",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "rawSql": "select\r\n    90 - elevation as \"r\",\r\n    azimut as \"theta\",\r\n    'G' || to_char(satellite, 'fm00') as \"satellite\",\r\n    '$constellation' as \"constellation\"\r\nfrom\r\n    skyplot\r\n    inner join station s on s.id = skyplot.station_id\r\n    inner join constellation c on c.id = skyplot.constellation_id\r\n    inner join station_network sn on skyplot.station_id = sn.station_id\r\n    inner join network n on sn.network_id = n.id\r\n    inner join skyplot_date sd on date_id = sd.id\r\nwhere\r\n    cs2 and\r\n    s.fullname = '$station' and\r\n    c.fullname = '$constellation' and\r\n    n.name = '$network' and\r\n    sd.date = '$day';"
    }
   ]
  },
  {
   "title": "CS5",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "rawSql": "select\r\n  90 - elevation as \"r\",\r\n  azimut as \"theta\",\r\n  'G' || to_char(satellite, 'fm00') as \"satellite\",\r\n  '$constellation' as \"constellation\"\r\nfrom\r\n  skyplot\r\n  inner join station s on s.id = skyplot.station_id\r\n  inner join constellation c on c.id = skyplot.constellation_id\r\n  inner join station_network sn on skyplot.station_id = sn.station_id\r\n  inner join network n on sn.network_id = n.id\r\n  inner join skyplot_date sd on date_id = sd.id\r\nwhere\r\n  cs5\r\n  and s.fullname = '$station'\r\n  and c.fullname = '$constellation'\r\n  and n.name = '$network'\r\n  and sd.date = '$day';"
    }
   ]
  },
  { "title": "Sources and explanations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Graph sources",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 37 },
   "options": {
    "content": "# Graph sources\n\n- Graphs are generated from the data quality metrics xtr files available at: \n[https://renag.resif.fr/pub/quality-check/full/{{year}}/{{number}}/{{fullname}}-{{day}}.xtr](https://renag.resif.fr/pub/quality-check/full/{{year}}/{{number}}/{{fullname}}-{{day}}.xtr)\n- The data quality metrics have been computed at the [RESIF-RENAG](http://doi.org/10.17616/R31NJN5L) data center using the [G-Nut/Anubis](https://gnutsoftware.com/software/anubis/) software\n- Input files are the daily RINEX 3 observation files available from:\n[https://renag.resif.fr/pub/rinex3/{{year}}/{{number}}/{{fullname}}_R_{{year}}{{number}}0000_01D_30S_MO.crx.gz](https://renag.resif.fr/pub/rinex3/{{year}}/{{number}}/{{fullname}}_R_{{year}}{{number}}0000_01D_30S_MO.crx.gz)\n"
   },
   "targets": [
    {
     "rawSql": "select\r\n    s.fullname,\r\n    split_part('$day', '-', 1) as year,\r\n    to_char('$day'::date - date_trunc('year', '$day'::date)::date + 1, 'fm000') as number,\r\n    '$day' as day\r\nfrom station s\r\n  inner join station_network sn on sn.station_id = s.id\r\n  inner join network n on n.id = sn.network_id\r\nwhere fullname = '$station'\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Explanations",
   "type": "text",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 37 },
   "options": {
    "content": "# Explanations\n\n## Skyplot view\n\nSky plots show satellite locations in elevation and azimuth from the antenna location.  \nThe metrics and positions are computed every 15 minutes.\n\n## Carrier-phase signal-to-noise ratio (dB-Hz)\n\nSignal strength of the modulated signal.\n\n## Pseudo-range multipath (cm)\n\nElongation of the signal arriving indirectly at the GNSS antenna.\n\n## Satellite cycle slips (%)\n\nRed dots shows satellite tracking interruption occurences.  \nEmpty view mean no cycle slip detected, or signal band not tracked.\n"
   }
  },
  {
   "title": "Used observables",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "select\r\n  c.fullname as \"Constellation\",\r\n  ot1.type as \"MP1\",\r\n  ot2.type as \"MP2\",\r\n  ot5.type as \"MP5\",\r\n  snr1.type as \"SNR1\",\r\n  snr2.type as \"SNR2\",\r\n  snr5.type as \"SNR5\"\r\nfrom\r\n  skyplot_used_band b\r\n  inner join skyplot_date sd on b.date_id = sd.id\r\n  inner join station s on b.station_id = s.id\r\n  inner join station_network sn on sn.station_id = s.id\r\n  inner join network n on n.id = sn.network_id\r\n  inner join constellation c on c.id = b.constellation_id\r\n  inner join observation_type ot1 on b.mp1_observation_type_id = ot1.id\r\n  inner join observation_type ot2 on ot2.id = b.mp2_observation_type_id\r\n  inner join observation_type ot5 on ot5.id = b.mp5_observation_type_id\r\n  inner join observation_type snr1 on snr1.id = b.sig2noise1_observation_type_id\r\n  inner join observation_type snr2 on snr2.id = b.sig2noise2_observation_type_id\r\n  inner join observation_type snr5 on snr5.id = b.sig2noise5_observation_type_id\r\nwhere\r\n  sd.date = '$day'\r\n  and s.fullname = '$station';"
    }
   ]
  }
 ]
}