version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss:9.5.2
    container_name: grafana
    restart: on-failure
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GF_SERVER_ENABLE_GZIP=true

      - GF_INSTALL_PLUGINS=nline-plotlyjs-panel,marcusolsson-dynamictext-panel

      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=host.docker.internal:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=m1m # TODO: change this

      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Géoazur
